"use client";

import { useState } from "react";
import {
  FileText,
  Brain,
  BarChart3,
  Download,
  Plus,
  X,
  ChevronDown,
} from "lucide-react";

interface Report {
  id: string;
  name: string;
  type: string;
  generatedAt: string;
  period: string;
  pageCount: number;
  status: "completed" | "generating" | "failed";
  autoGenerated: boolean;
}

const MOCK_REPORTS: Report[] = [
  {
    id: "R-001",
    name: "2026年4月 工程分析レポート",
    type: "工程分析",
    generatedAt: "2026-05-01 08:00",
    period: "2026年4月",
    pageCount: 24,
    status: "completed",
    autoGenerated: true,
  },
  {
    id: "R-002",
    name: "品川タワー 安全分析レポート",
    type: "安全分析",
    generatedAt: "2026-05-10 09:30",
    period: "2026年4月〜5月",
    pageCount: 18,
    status: "completed",
    autoGenerated: false,
  },
  {
    id: "R-003",
    name: "2026年Q1 総合報告書",
    type: "総合報告",
    generatedAt: "2026-04-05 10:00",
    period: "2026年1〜3月",
    pageCount: 52,
    status: "completed",
    autoGenerated: true,
  },
  {
    id: "R-004",
    name: "協力会社 品質分析レポート",
    type: "品質分析",
    generatedAt: "2026-05-15 14:00",
    period: "2026年1〜4月",
    pageCount: 31,
    status: "completed",
    autoGenerated: false,
  },
  {
    id: "R-005",
    name: "2026年4月 コスト分析レポート",
    type: "コスト分析",
    generatedAt: "2026-05-03 09:00",
    period: "2026年4月",
    pageCount: 20,
    status: "completed",
    autoGenerated: true,
  },
  {
    id: "R-006",
    name: "新宿ビル 工程分析レポート",
    type: "工程分析",
    generatedAt: "2026-05-20 11:00",
    period: "2026年3〜5月",
    pageCount: 0,
    status: "generating",
    autoGenerated: false,
  },
  {
    id: "R-007",
    name: "2026年3月 安全分析レポート",
    type: "安全分析",
    generatedAt: "2026-04-02 08:00",
    period: "2026年3月",
    pageCount: 16,
    status: "completed",
    autoGenerated: true,
  },
  {
    id: "R-008",
    name: "大阪ビル 総合報告書",
    type: "総合報告",
    generatedAt: "2026-05-18 15:30",
    period: "2026年2〜5月",
    pageCount: 0,
    status: "failed",
    autoGenerated: false,
  },
];

const STATUS_CONFIG = {
  completed: { label: "完了", color: "bg-green-100 text-green-700" },
  generating: { label: "生成中", color: "bg-blue-100 text-blue-700" },
  failed: { label: "失敗", color: "bg-red-100 text-red-700" },
};

const TYPE_COLORS: Record<string, string> = {
  工程分析: "bg-blue-100 text-blue-700",
  安全分析: "bg-red-100 text-red-700",
  品質分析: "bg-green-100 text-green-700",
  コスト分析: "bg-yellow-100 text-yellow-700",
  総合報告: "bg-purple-100 text-purple-700",
};

const REPORT_TYPES = [
  "工程分析",
  "安全分析",
  "品質分析",
  "コスト分析",
  "総合報告",
];

export default function AIReportsPage() {
  const [showModal, setShowModal] = useState(false);
  const [newType, setNewType] = useState("工程分析");
  const [newPeriod, setNewPeriod] = useState("");

  const thisMonth = MOCK_REPORTS.filter((r) =>
    r.generatedAt.startsWith("2026-05"),
  ).length;
  const autoRate = Math.round(
    (MOCK_REPORTS.filter((r) => r.autoGenerated).length / MOCK_REPORTS.length) *
      100,
  );
  const completedTimes = MOCK_REPORTS.filter(
    (r) => r.status === "completed",
  ).map(() => Math.floor(Math.random() * 20 + 5));
  const avgTime = Math.round(
    completedTimes.reduce((a, b) => a + b, 0) / completedTimes.length,
  );

  return (
    <div className="p-6 space-y-6">
      {/* ヘッダー */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">AI生成レポート</h1>
          <p className="text-sm text-gray-500 mt-1">
            AIによる各種分析レポートの自動生成
          </p>
        </div>
        <button
          onClick={() => setShowModal(true)}
          className="flex items-center gap-2 bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 transition-colors text-sm"
        >
          <Plus className="w-4 h-4" />
          新規生成
        </button>
      </div>

      {/* 統計カード */}
      <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
        <div className="bg-white rounded-xl p-4 shadow-sm border border-gray-100">
          <div className="flex items-center gap-3">
            <div className="p-2 bg-blue-50 rounded-lg">
              <FileText className="w-5 h-5 text-blue-600" />
            </div>
            <div>
              <p className="text-xs text-gray-500">今月生成数</p>
              <p className="text-2xl font-bold text-gray-900">{thisMonth}</p>
            </div>
          </div>
        </div>
        <div className="bg-white rounded-xl p-4 shadow-sm border border-gray-100">
          <div className="flex items-center gap-3">
            <div className="p-2 bg-green-50 rounded-lg">
              <Brain className="w-5 h-5 text-green-600" />
            </div>
            <div>
              <p className="text-xs text-gray-500">自動生成率</p>
              <p className="text-2xl font-bold text-gray-900">{autoRate}%</p>
            </div>
          </div>
        </div>
        <div className="bg-white rounded-xl p-4 shadow-sm border border-gray-100">
          <div className="flex items-center gap-3">
            <div className="p-2 bg-purple-50 rounded-lg">
              <BarChart3 className="w-5 h-5 text-purple-600" />
            </div>
            <div>
              <p className="text-xs text-gray-500">平均生成時間</p>
              <p className="text-2xl font-bold text-gray-900">{avgTime}分</p>
            </div>
          </div>
        </div>
      </div>

      {/* レポート一覧テーブル */}
      <div className="bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden">
        <div className="px-5 py-4 border-b border-gray-100">
          <h2 className="font-semibold text-gray-800">レポート一覧</h2>
        </div>
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead className="bg-gray-50 border-b border-gray-200">
              <tr>
                <th className="text-left px-4 py-3 font-medium text-gray-600">
                  レポート名
                </th>
                <th className="text-left px-4 py-3 font-medium text-gray-600">
                  種別
                </th>
                <th className="text-left px-4 py-3 font-medium text-gray-600">
                  生成日時
                </th>
                <th className="text-left px-4 py-3 font-medium text-gray-600">
                  対象期間
                </th>
                <th className="text-left px-4 py-3 font-medium text-gray-600">
                  ページ数
                </th>
                <th className="text-left px-4 py-3 font-medium text-gray-600">
                  生成方法
                </th>
                <th className="text-left px-4 py-3 font-medium text-gray-600">
                  ステータス
                </th>
                <th className="text-left px-4 py-3 font-medium text-gray-600">
                  操作
                </th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100">
              {MOCK_REPORTS.map((report) => (
                <tr
                  key={report.id}
                  className="hover:bg-gray-50 transition-colors"
                >
                  <td className="px-4 py-3 font-medium text-gray-900">
                    {report.name}
                  </td>
                  <td className="px-4 py-3">
                    <span
                      className={`px-2 py-0.5 rounded text-xs font-medium ${TYPE_COLORS[report.type] ?? "bg-gray-100 text-gray-600"}`}
                    >
                      {report.type}
                    </span>
                  </td>
                  <td className="px-4 py-3 text-gray-500 text-xs whitespace-nowrap">
                    {report.generatedAt}
                  </td>
                  <td className="px-4 py-3 text-gray-600 text-xs">
                    {report.period}
                  </td>
                  <td className="px-4 py-3 text-gray-700">
                    {report.pageCount > 0 ? `${report.pageCount}p` : "—"}
                  </td>
                  <td className="px-4 py-3">
                    {report.autoGenerated ? (
                      <span className="flex items-center gap-1 text-xs text-blue-600">
                        <Brain className="w-3 h-3" />
                        自動
                      </span>
                    ) : (
                      <span className="text-xs text-gray-500">手動</span>
                    )}
                  </td>
                  <td className="px-4 py-3">
                    <span
                      className={`px-2 py-0.5 rounded-full text-xs font-medium ${STATUS_CONFIG[report.status].color}`}
                    >
                      {STATUS_CONFIG[report.status].label}
                    </span>
                  </td>
                  <td className="px-4 py-3">
                    {report.status === "completed" && (
                      <button className="flex items-center gap-1 text-xs text-blue-600 hover:text-blue-800 border border-blue-200 rounded px-2 py-1 hover:bg-blue-50 transition-colors">
                        <Download className="w-3 h-3" />
                        DL
                      </button>
                    )}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
        <div className="px-4 py-3 border-t border-gray-100 text-sm text-gray-500">
          {MOCK_REPORTS.length}件
        </div>
      </div>

      {/* 新規生成モーダル */}
      {showModal && (
        <div className="fixed inset-0 bg-black/40 flex items-center justify-center z-50">
          <div className="bg-white rounded-xl shadow-xl p-6 w-full max-w-md mx-4">
            <div className="flex items-center justify-between mb-4">
              <h3 className="text-lg font-semibold text-gray-900">
                新規レポート生成
              </h3>
              <button
                onClick={() => setShowModal(false)}
                className="text-gray-400 hover:text-gray-600"
              >
                <X className="w-5 h-5" />
              </button>
            </div>
            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  レポート種別
                </label>
                <div className="relative">
                  <select
                    value={newType}
                    onChange={(e) => setNewType(e.target.value)}
                    className="w-full appearance-none border border-gray-200 rounded-lg px-4 py-2.5 pr-10 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
                  >
                    {REPORT_TYPES.map((t) => (
                      <option key={t} value={t}>
                        {t}
                      </option>
                    ))}
                  </select>
                  <ChevronDown className="absolute right-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400 pointer-events-none" />
                </div>
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  対象期間
                </label>
                <input
                  type="text"
                  placeholder="例: 2026年5月"
                  value={newPeriod}
                  onChange={(e) => setNewPeriod(e.target.value)}
                  className="w-full border border-gray-200 rounded-lg px-4 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
                />
              </div>
              <div className="flex gap-3 pt-2">
                <button
                  onClick={() => setShowModal(false)}
                  className="flex-1 border border-gray-200 text-gray-700 py-2.5 rounded-lg hover:bg-gray-50 transition-colors text-sm"
                >
                  キャンセル
                </button>
                <button
                  onClick={() => setShowModal(false)}
                  className="flex-1 bg-blue-600 text-white py-2.5 rounded-lg hover:bg-blue-700 transition-colors text-sm font-medium flex items-center justify-center gap-2"
                >
                  <Brain className="w-4 h-4" />
                  生成開始
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
